"""empty message

Revision ID: 135420fe1230
Revises: d14c15546af0
Create Date: 2026-07-03 12:56:07.410404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135420fe1230'
down_revision = 'd14c15546af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameItem', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
