"""empty message

Revision ID: 3b91c6bbb2a4
Revises: 135420fe1230
Create Date: 2026-07-03 14:20:18.659606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b91c6bbb2a4'
down_revision = '135420fe1230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ducats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameItem', schema=None) as batch_op:
        batch_op.drop_column('ducats')

    # ### end Alembic commands ###
