"""empty message

Revision ID: d14c15546af0
Revises: 
Create Date: 2026-07-02 20:55:17.162845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14c15546af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InventoryPart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InventoryPart', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
